services:
  headscale:
    image: headscale/headscale:0.28.0
    restart: unless-stopped
    command: serve
    volumes:
      - ./config.yaml:/etc/headscale/config.yaml:ro
      - ./acl.json:/etc/headscale/acl.json:ro
      - headscale-data:/var/lib/headscale
    ports:
      - "127.0.0.1:18080:8080" # hanya untuk diakses cloudflared terpisah di host yang sama
    environment:
      - TZ=Asia/Makassar

volumes:
  headscale-data:
